<<<<<<< HEAD
# Generated by Django 6.0.4 on 2026-04-26 11:28

import django.db.models.deletion
from django.conf import settings
=======
# Generated by Django 5.2.8 on 2026-04-26 10:53

import django.db.models.deletion
>>>>>>> ce273ed71ba1f53413829f679ae12dd266591d37
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
=======
>>>>>>> ce273ed71ba1f53413829f679ae12dd266591d37
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
<<<<<<< HEAD
                ('description', models.TextField(blank=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
=======
                ('duration', models.IntegerField()),
                ('total_questions', models.IntegerField()),
                ('is_active', models.BooleanField(default=False)),
                ('negative_marking', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('student_id', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=100)),
>>>>>>> ce273ed71ba1f53413829f679ae12dd266591d37
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
<<<<<<< HEAD
                ('option_a', models.CharField(max_length=200)),
                ('option_b', models.CharField(max_length=200)),
                ('option_c', models.CharField(max_length=200)),
                ('option_d', models.CharField(max_length=200)),
                ('correct_option', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
=======
                ('option1', models.CharField(max_length=200)),
                ('option2', models.CharField(max_length=200)),
                ('option3', models.CharField(max_length=200)),
                ('option4', models.CharField(max_length=200)),
                ('correct', models.CharField(max_length=200)),
                ('marks', models.IntegerField(default=1)),
>>>>>>> ce273ed71ba1f53413829f679ae12dd266591d37
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='exam.exam')),
            ],
        ),
        migrations.CreateModel(
<<<<<<< HEAD
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('taken_at', models.DateTimeField(auto_now_add=True)),
=======
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0)),
                ('total', models.FloatField(default=0)),
                ('percentage', models.FloatField(default=0)),
                ('is_submitted', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(null=True)),
                ('submitted_at', models.DateTimeField(null=True)),
>>>>>>> ce273ed71ba1f53413829f679ae12dd266591d37
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.student')),
            ],
        ),
<<<<<<< HEAD
=======
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_option', models.CharField(blank=True, max_length=200)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.question')),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.result')),
            ],
        ),
>>>>>>> ce273ed71ba1f53413829f679ae12dd266591d37
    ]
