# Generated by Django 6.0.4 on 2026-04-30 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_alter_result_options_remove_question_correct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='allow_retake',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exam',
            name='exam_type',
            field=models.CharField(choices=[('theory', 'Theory'), ('practical', 'Practical')], default='theory', max_length=20),
        ),
        migrations.AddField(
            model_name='exam',
            name='instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='marks_per_question',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='exam',
            name='max_attempts',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='exam',
            name='passing_marks',
            field=models.FloatField(default=0),
        ),
    ]
