# Generated by Django 6.0.4 on 2026-04-30 07:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_alter_result_time_taken_practicalquestion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='practicalanswer',
            name='code',
        ),
        migrations.AddField(
            model_name='practicalanswer',
            name='file',
            field=models.FileField(default=django.utils.timezone.now, upload_to='practical_answers/'),
            preserve_default=False,
        ),
    ]
