# Generated by Django 6.0.4 on 2026-04-30 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_remove_practicalanswer_code_practicalanswer_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='practicalquestion',
            name='exam',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='allow_retake',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='exam_type',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='instructions',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='marks_per_question',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='max_attempts',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='passing_marks',
        ),
        migrations.AlterField(
            model_name='result',
            name='time_taken',
            field=models.IntegerField(default=0, help_text='Seconds'),
        ),
        migrations.DeleteModel(
            name='PracticalAnswer',
        ),
        migrations.DeleteModel(
            name='PracticalQuestion',
        ),
    ]
